### ISSUE TITLE
Driver is not fully isolated from contexts

### ISSUE THREAD

**Issue by pamil** [Behat/Symfony2Extension#112]
The current driver shares the same kernel with the one used to inject services into contexts. The kernel is restarted:

 - just before second and every another request is made
 - after scenario

This means that the state set in contexts on services retrieved from container before first request also modifies the way the first request is handled (which may give us different results).

The solution is to duplicate the kernel and use that one only for the driver.

**Comment by sroze** [comment]
To me it is the expected behaviour as we can't rely that the user will have a stable kernel across requests. Ideally we wouldn't even have to reboot the kernel as your services should not contain state that changes the way you handle a request IMHO.

I'm not sure what are you expecting from this issue?

**Comment by pamil** [comment]
I'm asking whether are you interested in providing an isolated driver in this extension.

In the ideal world it would not be needed, but sometimes the bundle you depend on isn't that good and its services contain some state. My proposition is to made the changes in contexts do not affect the behaviour of the first request.

**Comment by stof** [comment]
Isolating the kernel used in contexts from the one used by the driver is something I thought about already.
I don't know yet how this can be done for the migration path though, to avoid BC breaks.

**Comment by sroze** [comment]
This is definitely not something that should be by default, so I see no point of any migration path. In order to be able to easily to domain testing with Behat and Symfony, it is super easy to update some in-memory repositories from the context file and then send a request to the kernel, where the same repositories will be used.

Tho, it makes sense to support this isolation between the contexts and the application itself. To do that, we probably have to boot the application twice, and use the service container of the "first booted kernel" to populate the contexts.
