### ISSUE TITLE
Symfony3 Directory Structure

### ISSUE THREAD

**Issue by noetix** [Behat/Symfony2Extension#64]
When using Symfony's new directory structure, the extension creates new cache/logs directories in `app` and ignores the ones in `var`.

**Comment by stof** [comment]
Closing because this is a bug in SensioDistributionBundle when initializing the Symfony2 directory structure: https://github.com/sensiolabs/SensioDistributionBundle/issues/142#issuecomment-68713604. The fix is given in the comment of @smatyas in https://github.com/Behat/Symfony2Extension/issues/69#issuecomment-69921141.
